### ISSUE TITLE
`bundle` never ends.

### ISSUE THREAD

**Issue by yokozawa0701** [area17/blast#132]
refs: #100

I tried to install blast and run `php artisan blast:launch` but this launch didn't work well like below.
I waited for this bundle for a long time, but it never ended.

```sh
$ php artisan blast:launch
0/2 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░] Installing npm dependencies...

added 1089 packages, and audited 1090 packages in 10s

199 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (8 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

1/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░] Generating Stories...
2/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] Setup Complete. Booting Storybook and watching stories.
> @area17/blast@1.0.0 storybook
> concurrently --i -c "red,blue,yellow" -n storybook,watch-components,watch-data "storybook dev --quiet -s $STORYBOOK_STATIC_PATH -p $STORYBOOK_PORT" "npm run watch-components" "npm run watch-data"

[watch-data]
[watch-data] > @area17/blast@1.0.0 watch-data
[watch-data] > chokidar "$COMPONENTPATH/data/**/*.php" "$COMPONENTPATH/**/*.md" -d 0 -c "cd $PROJECTPATH && php artisan blast:generate-stories;"
[watch-data]
[watch-components]
[watch-components] > @area17/blast@1.0.0 watch-components
[watch-components] > chokidar "$COMPONENTPATH/**/*.blade.php" -d 0 -c "cd $PROJECTPATH && php artisan blast:generate-stories --watchEvent={event} -- '{path}';"
[watch-components]
[watch-data] Watching "/resources/views/stories/data/**/*.php", "/resources/views/stories/**/*.md" ..
[watch-components] Watching "/resources/views/stories/**/*.blade.php" ..
[storybook] @storybook/cli v7.1.1
[storybook]
[storybook]
[storybook] attention => Storybook now collects completely anonymous telemetry regarding usage.
[storybook] This information is used to shape Storybook's roadmap and prioritize features.
[storybook] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[storybook] https://storybook.js.org/telemetry
[storybook]
[storybook] info => Serving static files from ./../../../public at /
[storybook] info => Starting manager..
[storybook] info Addon-docs: using MDX2
[storybook] info => Using implicit CSS loaders
[storybook] info => Using default Webpack5 setup
[storybook] <i> [webpack-dev-middleware] wait until bundle finished
```

### versions

- node:  18.20.3
- Laravel: 9.19
- php: 8.2.17

### tailwind.config.js

```js
const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require("@tailwindcss/forms")],
};
```

Thanks.

**Comment by mrtimbrook** [comment]
Did you try going to localhost:6006? Storybook moved the dev server info table that shows when Storybook launches to be hidden behind the `--quiet` flag (https://github.com/storybookjs/storybook/pull/23133) so it may have finished and be working but doesn't notify you.

I've been looking into ways to reintroduce it but I may just remove the `--quiet` flag for now.

**Comment by yokozawa0701** [comment]
@mrtimbrook 

Oh, I could access! Thanks!
I'll close this issue.

**Comment by yokozawa0701** [comment]
@mrtimbrook 

I'm sorry but I can open storybook dashboard but I bumped into another error below.
Do yon know how to resolve it?

```
TypeError: Failed to fetch
    at defaultFetchStoryHtml (http://127.0.0.1:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-generated-config-entry_js-node_mod-3433b1.iframe.bundle.js:1581:269)
    at renderToCanvas (http://127.0.0.1:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-generated-config-entry_js-node_mod-3433b1.iframe.bundle.js:1581:1045)
    at StoryRender.renderToScreen (http://127.0.0.1:6006/sb-preview/runtime.js:94:2702)
    at http://127.0.0.1:6006/sb-preview/runtime.js:74:10850
    at StoryRender.runPhase (http://127.0.0.1:6006/sb-preview/runtime.js:74:8772)
    at StoryRender.render (http://127.0.0.1:6006/sb-preview/runtime.js:74:10783)
```

<img width="1468" alt="Screenshot 2024-06-03 at 23 03 59" src="https://github.com/area17/blast/assets/8081222/5707b9ab-0528-4867-8452-93f31f3c52c1">

**Comment by yokozawa0701** [comment]
refs: https://github.com/area17/blast/issues/35#issuecomment-1483945224
I could resolved after set `APP_URL=http://localhost:8000` to .env.
Thanks
