### ISSUE TITLE
Webpack update not working with Sail Laravel

### ISSUE THREAD

**Issue by wireless25** [area17/blast#22]
I use [Laravel Sail](https://laravel.com/docs/8.x/sail) to run my project locally. Initial launch with `blast:launch` works fine, but as soon as some code is changed the node process throws an error.

```bash
[1] /var/www/html/vendor/area17/blast/node_modules/chokidar-cli/utils.js:16
[1]         throw new Error('$SHELL environment variable is not set.');
[1]               ^
[1] 
[1] Error: $SHELL environment variable is not set.
[1]     at Object.run (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/utils.js:16:15)
[1]     at run (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/index.js:225:18)
[1]     at FSWatcher.<anonymous> (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/index.js:164:13)
[1]     at FSWatcher.emit (node:events:378:20)
[1]     at FSWatcher.emitWithAll (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/node_modules/chokidar/index.js:541:32)
[1]     at FSWatcher._emit (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/node_modules/chokidar/index.js:632:8)
[1]     at listener (/var/www/html/vendor/area17/blast/node_modules/chokidar-cli/node_modules/chokidar/lib/nodefs-handler.js:370:20)
[1] npm ERR! code 1
[1] npm ERR! path /var/www/html/vendor/area17/blast
[1] npm ERR! command failed
[1] npm ERR! command sh -c chokidar "$COMPONENTPATH/**/*.blade.php" -d 0 -c "cd $PROJECTPATH && php artisan blast:generate-stories --watchEvent={event} -- '{path}';"
[1] 
npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/sail/.npm/_logs/2021-11-09T14_02_55_395Z-debug.log
[1] npm run watch-components exited with code 1
```

Looks like chokidar is exiting because env var `$SHELL` is not present. I echoed `$SHELL` in the Sail shell, and its defined as `/bin/bash`.

**Comment by pboivin** [comment]
Hi @wireless25, I ran into this issue recently running Chokidar on Sail in another context. I was able to work around it by "exporting" the variable before running my command, e.g. :
```
export SHELL=/bin/bash && php artisan blast:launch
```

**Comment by wireless25** [comment]
@pboivin lifesaver! this works perfectly, now the hot reloading works like a charm.

Therefore I assume there is nothing to fix for Blast, I'll close this issue.
